- hosts: 127.0.0.1
  tasks:
    - name: login
      check_point_mgmt:
        command: login
        parameters:
          username: '{{mgmt_user}}'
          password: '{{mgmt_password}}'
          management: '{{mgmt_server}}'
        fingerprint: "{{mgmt_finger_Print}}"
      register: login_response
    - name: publish
      check_point_mgmt:
        command: publish
        session-data: '{{login_response}}'
    - name: install policy
      check_point_mgmt:
        command: install-policy
        parameters:
          policy-package: FirstPolicy
        session-data: '{{login_response}}'
    - name: logout
      check_point_mgmt:
        command: logout
        session-data: '{{login_response}}'
