---
- hosts: "localhost"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{mgmt_finger_Print}}"
    register: login_response
  - name: "Publish"
    command: mgmt publish
    session-data: "{{login_response}}"
- name: "logout"
    check_point_mgmt:
      command: logout
      session-data: '{{login_response}}'
